_adj:
  range:
    max: 500
    min: 0
  value:
    black_point: 302
    brightness: 115
    brilliance: 106
    contrast: 146
    exposure: 104
    highlights: 154
    noise_reduction: 45
    shadows: 118
    sharpness: 67
adaptive_threshold:
  range:
    max: 255
    min: 0
  value:
    block_size: 188
    c: 0
gaussian_blur:
  range:
    max: 255
    min: 10
  value:
    ksize: 10
threshold:
  range:
    max: 255
    min: 0
  value:
    max: 255
    min: 85
