after_blur: 51
at_dilate: 9
at_th_max: 255
at_th_min: 202
bin_blur: 23
block_size: 18
blur: 5
brightness: 46
c: 5
canny_max: 50
canny_min: 7
contrast: 44
gamma: 42
img_idx: 2
iterations: 0
kernel_size: 1
max_radius: 38
max_value: 211
min_dist: 53
min_radius: 19
param1: 16
param2: 10
threshold_max: 184
threshold_min: 224
