black_point: 200
brightness: 181
brilliance: 92
contrast: 200
exposure: 99
highlights: 91
img_idx: 1
max_radius: 41
min_dist: 55
min_radius: 24
noise_reduction: 121
param1: 9
param2: 13
shadows: 78
sharpness: 96
