_adj:
  range:
    max: 500
    min: 0
  show: false
  value:
    black_point: 302
    brightness: 115
    brilliance: 106
    contrast: 146
    exposure: 104
    highlights: 154
    noise_reduction: 45
    shadows: 118
    sharpness: 67
_adj2:
  range:
    max: 500
    min: 0
  show: true
  value:
    black_point: 128
    brightness: 113
    brilliance: 101
    contrast: 81
    exposure: 117
    highlights: 113
    noise_reduction: 129
    shadows: 72
    sharpness: 181
adaptive_threshold:
  range:
    max: 255
    min: 0
  show: false
  value:
    block_size: 188
    c: 0
gaussian_blur:
  range:
    max: 255
    min: 10
  show: false
  value:
    ksize: 10
hough_circle:
  range:
    max: 255
    min: 0
  show: false
  value:
    max_radius: 34
    min_dist: 46
    min_radius: 27
    param1: 60
    param2: 11
imdiff:
  range:
    max: 255
    min: 0
  show: true
  value:
    blur: 51
    iter: 0
    ksize: 2
    max: 255
    min: 45
sj:
  range:
    max: 255
    min: 0
  show: true
  value:
    black_point: 66
    brightness: 50
    contrast: 53
    definition: 50
    exposure: 48
    highlights: 50
    max_radius: 37
    min_dist: 56
    min_radius: 33
    param1: 26
    param2: 1
    shadows: 51
    sharpness: 0
    threshold_value: 117
thresh_2:
  range:
    max: 255
    min: 0
  show: true
  value:
    max: 255
    min: 107
threshold:
  range:
    max: 255
    min: 0
  show: false
  value:
    max: 25
    min: 85
